### ISSUE TITLE
如果开机后才联网，速度不显示

### ISSUE THREAD

**Issue by EpLiar** [ChDC/ChDCStatMenus#2]
http://epichan.pro/QQ%E6%88%AA%E5%9B%BE20170713113319.png

如图

方法如下：
开机前断开无线局域网，并且拔掉网线，开机后打开chdc，插网线，速度显示bug

**Comment by ChDC** [comment]
抱歉，我这边开机前断网，然后开机打开程序，插网线，然后速度没有问题啊。然后我复查了下代码，逻辑啥的都没问题啊。抱歉，不能重现你的 BUG。你要不再试试？
我的是这样的：
![_20170713142827](https://user-images.githubusercontent.com/20246067/28153363-9cb05602-67d7-11e7-867a-6b29a3c03983.png)
看你的截图发现一个问题：你的任务栏在下面，我的任务栏在上面，然后你的弹窗就会跑上面去了。我任务栏依着 Mac 的习惯都在上面的。有空我会修复下这个问题的。
还有之前开机启动的问题。。。

**Comment by EpLiar** [comment]
那应该是我用了1.0版本的……
卸了重装后再测试了一下，果然没事了
哎以后我会多多在自己身上找问题的，打扰了
